/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AjoutRelation;

import Autre.AjoutDAR;
import Listage.List;
import NOSQL.Connexion;
import Personnages.Passager;
import Vols.Avion;
import Vols.DAR;
import Vols.DPR;
import Vols.Depart;
import com.mongodb.BasicDBObject;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;
import java.awt.event.KeyEvent;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Ben Abdallah Youssef
 */
public class qqqqq extends javax.swing.JFrame {

    /**
     * Creates new form qqqqq
     */
    public qqqqq() throws UnknownHostException {
        initComponents();
        chargerListAvion();
        chargerListDepart();
        chargerTout();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        try {
            ajoutVTR1 = new AjoutRelation.AjoutVTR();
        } catch (java.net.UnknownHostException e1) {
            e1.printStackTrace();
        }
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jour = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        annee = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        mois = new javax.swing.JTextField();
        qc = new javax.swing.JTextField();
        listA = new javax.swing.JComboBox();
        listD = new javax.swing.JComboBox();
        type = new javax.swing.JTextField();
        capacite = new javax.swing.JTextField();
        ajouter = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        mois1 = new javax.swing.JTextField();
        listD1 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        listP = new javax.swing.JComboBox();
        ajouter1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        nom = new javax.swing.JTextField();
        jour1 = new javax.swing.JTextField();
        prenom = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        numTel = new javax.swing.JTextField();
        annee1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        adresse = new javax.swing.JTextField();
        listPP = new javax.swing.JComboBox();
        jPanel7 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel7.setText("Capacité");

        jLabel3.setText("Numero Avion");

        jour.setToolTipText("Jour");
        jour.setEnabled(false);
        jour.setName(""); // NOI18N
        jour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jourMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jourMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jourMouseReleased(evt);
            }
        });
        jour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jourActionPerformed(evt);
            }
        });
        jour.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jourKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jourKeyTyped(evt);
            }
        });

        jLabel5.setText("Date");

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(204, 204, 255));
        jTextField1.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        jTextField1.setText("Ajout Depart Avion Relation");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        annee.setToolTipText("Annee");
        annee.setEnabled(false);
        annee.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                anneeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                anneeKeyTyped(evt);
            }
        });

        jLabel4.setText("Quantite Carburant");

        mois.setToolTipText("Mois");
        mois.setEnabled(false);
        mois.setName(""); // NOI18N
        mois.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                moisMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                moisMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                moisMouseReleased(evt);
            }
        });
        mois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moisActionPerformed(evt);
            }
        });
        mois.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                moisKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                moisKeyTyped(evt);
            }
        });

        qc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qcKeyTyped(evt);
            }
        });

        listA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listAActionPerformed(evt);
            }
        });

        listD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listDActionPerformed(evt);
            }
        });

        type.setEnabled(false);
        type.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                typeKeyReleased(evt);
            }
        });

        capacite.setEnabled(false);
        capacite.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                capaciteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                capaciteKeyTyped(evt);
            }
        });

        ajouter.setText("Ajouter");
        ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterActionPerformed(evt);
            }
        });

        jLabel6.setText("Type");

        jLabel2.setText("Numero Depart");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(qc, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(163, 163, 163))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(type, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(capacite, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(listA, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(listD, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jour, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(mois, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(annee, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(ajouter)
                        .addGap(230, 230, 230)))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(listD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(annee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(capacite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(ajouter))
        );

        jTabbedPane2.addTab("tab1", jPanel5);

        mois1.setToolTipText("Mois");
        mois1.setEnabled(false);
        mois1.setName(""); // NOI18N
        mois1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mois1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mois1MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                mois1MouseReleased(evt);
            }
        });
        mois1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mois1ActionPerformed(evt);
            }
        });
        mois1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mois1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mois1KeyTyped(evt);
            }
        });

        listD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listD1ActionPerformed(evt);
            }
        });

        jLabel8.setText("Numero Depart");

        listP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listPActionPerformed(evt);
            }
        });

        ajouter1.setText("Ajouter");
        ajouter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouter1ActionPerformed(evt);
            }
        });

        jLabel9.setText("Prenom");

        jLabel10.setText("Numero CIN Personne");

        jLabel11.setText("Num TEL");

        jLabel12.setText("Adresse");

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(204, 204, 255));
        jTextField2.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        jTextField2.setText("Ajout Depart Passager Relation");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        nom.setEnabled(false);
        nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomActionPerformed(evt);
            }
        });
        nom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nomKeyReleased(evt);
            }
        });

        jour1.setToolTipText("Jour");
        jour1.setEnabled(false);
        jour1.setName(""); // NOI18N
        jour1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jour1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jour1MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jour1MouseReleased(evt);
            }
        });
        jour1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jour1ActionPerformed(evt);
            }
        });
        jour1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jour1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jour1KeyTyped(evt);
            }
        });

        prenom.setEnabled(false);
        prenom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                prenomKeyReleased(evt);
            }
        });

        jLabel13.setText("Date");

        numTel.setEnabled(false);
        numTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                numTelKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numTelKeyTyped(evt);
            }
        });

        annee1.setToolTipText("Annee");
        annee1.setEnabled(false);
        annee1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                annee1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                annee1KeyTyped(evt);
            }
        });

        jLabel14.setText("Nom");

        adresse.setEnabled(false);
        adresse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                adresseKeyReleased(evt);
            }
        });

        listPP.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Navigant", "Non Navigant", "Passager", "Personnel", "Pilote" }));
        listPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listPPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 757, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addComponent(jLabel11)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel14)
                                        .addComponent(jLabel9))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(listP, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(prenom, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(adresse, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(numTel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(56, 56, 56)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(listPP, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(45, 45, 45)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(listD1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                            .addComponent(jLabel13)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jour1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(mois1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(annee1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addComponent(ajouter1)
                                    .addGap(0, 0, Short.MAX_VALUE)))))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 318, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(listD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10)
                                .addComponent(listPP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel14))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(adresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel12))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(numTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel11)))
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jour1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13)
                                    .addComponent(annee1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mois1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(listP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(170, 170, 170)
                            .addComponent(ajouter1)))
                    .addGap(16, 16, 16)))
        );

        jTabbedPane2.addTab("tab2", jPanel6);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 757, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 318, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        jTabbedPane2.addTab("tab3", jPanel7);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        jTabbedPane1.addTab("tab1", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 762, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 346, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab2", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 762, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 346, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab3", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 762, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 346, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab4", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 void chargerListPersonne() throws UnknownHostException
    {
    Connexion connexion = new Connexion("Airport");
    String collection = listPP.getSelectedItem().toString();
    if(collection.equals("Non Navigant")) collection = "NonNavigant";
    DBCursor list = connexion.getListe(collection);
    List l =  new List(list.count());
    String listAvion[]=l.remplirPersonne(list);
    for(int i=0;i<listAvion.length;i++)
    listP.addItem(listAvion[i]);    
    }
  
     void chargerListAvion() throws UnknownHostException
    {
    Connexion connexion = new Connexion("Airport");
    DBCursor list = connexion.getListe("Avion");
    List l =  new List(list.count());
    String listAvion[]=l.remplirByNum(list);
    for(int i=0;i<listAvion.length;i++)
    listA.addItem(listAvion[i]);
    
    }
    
    void chargerListDepart() throws UnknownHostException
    {
    Connexion connexion = new Connexion("Airport");
    DBCursor list = connexion.getListe("Depart");
    List l =  new List(list.count());
    String listAvion[]=l.remplirByNum(list);
    for(int i=0;i<listAvion.length;i++)
    listD.addItem(listAvion[i]);    
    }
    
    void chargerTout() throws UnknownHostException
    {
    Connexion connexion = new Connexion("Airport");
    if(listA.getSelectedIndex()>=0)
    {
    DBCursor list = connexion.findListe("Avion",new BasicDBObject().append("num",listA.getSelectedItem().toString()));
    DBObject object = list.next();
    type.setText(object.get("type").toString());
    capacite.setText(object.get("capacite").toString());
    }
    if(listD.getSelectedIndex()>=0)
    {
    DBCursor list = connexion.findListe("Depart",new BasicDBObject().append("num",listD.getSelectedItem().toString()));
    DBObject object = list.next();
    jour.setText(object.get("jour").toString());
    mois.setText(object.get("mois").toString());
    annee.setText(object.get("annee").toString());
    }
    }
    
    private void jourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jourMouseClicked

    }//GEN-LAST:event_jourMouseClicked

    private void jourMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jourMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jourMouseExited

    private void jourMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jourMouseReleased

    }//GEN-LAST:event_jourMouseReleased

    private void jourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jourActionPerformed

    private void jourKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jourKeyReleased

    }//GEN-LAST:event_jourKeyReleased

    private void jourKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jourKeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE )||jour.getText().length()==2)
        {   getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jourKeyTyped

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void anneeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_anneeKeyReleased

    }//GEN-LAST:event_anneeKeyReleased

    private void anneeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_anneeKeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE)||annee.getText().length()==4)
        {   getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_anneeKeyTyped

    private void moisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moisMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_moisMouseClicked

    private void moisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moisMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_moisMouseExited

    private void moisMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moisMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_moisMouseReleased

    private void moisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moisActionPerformed

    private void moisKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_moisKeyReleased

    }//GEN-LAST:event_moisKeyReleased

    private void moisKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_moisKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE )||mois.getText().length()==2)
        {   getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_moisKeyTyped

    private void qcKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qcKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE)|| qc.getText().length()==5)
        {   getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_qcKeyTyped

    private void listAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listAActionPerformed
        try {
            chargerTout();        // TODO add your handling code here:
        } catch (UnknownHostException ex) {
            Logger.getLogger(AjoutDAR.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_listAActionPerformed

    private void listDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listDActionPerformed
        try {
            chargerTout();        // TODO add your handling code here:
        } catch (UnknownHostException ex) {
            Logger.getLogger(AjoutDAR.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_listDActionPerformed

    private void typeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_typeKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_typeKeyReleased

    private void capaciteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_capaciteKeyReleased

    }//GEN-LAST:event_capaciteKeyReleased

    private void capaciteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_capaciteKeyTyped

    }//GEN-LAST:event_capaciteKeyTyped

    private void ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterActionPerformed

        if(qc.getText().length()==0)
        {
            JOptionPane.showMessageDialog(null, "*****  Saisir Le Quantite De Carburant  *****");

        } else
        {
            try {
                //boolean r=true;
                Avion A = new Avion(listA.getSelectedItem().toString());
                Depart D = new Depart(listD.getSelectedItem().toString());

                DAR dar = new DAR(D,A,qc.getText().toUpperCase());
                if (dar.rechercheDepart("DAR"))
                {
                    dar.ajouter("DAR");
                    JOptionPane.showMessageDialog(null, "*****  Relation Ajouter  *****");
                    qc.setText("");
                }
                else JOptionPane.showMessageDialog(null, "Deja Existe");

            }   catch (UnknownHostException ex) {
                Logger.getLogger(AjoutDAR.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_ajouterActionPerformed

    private void mois1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mois1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mois1MouseClicked

    private void mois1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mois1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_mois1MouseExited

    private void mois1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mois1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_mois1MouseReleased

    private void mois1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mois1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mois1ActionPerformed

    private void mois1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mois1KeyReleased

    }//GEN-LAST:event_mois1KeyReleased

    private void mois1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mois1KeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE )||mois.getText().length()==2)
        {   getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_mois1KeyTyped

    private void listD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listD1ActionPerformed
        try {
            chargerTout();        // TODO add your handling code here:
        } catch (UnknownHostException ex) {
            Logger.getLogger(AjoutDPR.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_listD1ActionPerformed

    private void listPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listPActionPerformed
        try {
            chargerTout();        // TODO add your handling code here:
        } catch (UnknownHostException ex) {
            Logger.getLogger(AjoutDPR.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_listPActionPerformed

    private void ajouter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouter1ActionPerformed

        try {

            Passager P = new Passager(listP.getSelectedItem().toString());
            Depart D = new Depart(listD.getSelectedItem().toString());

            String collection = listPP.getSelectedItem().toString();
            DPR dpr = new DPR(D,P,collection);
            if (dpr.rechercheType("DPR"))
            {

                if(collection.equals("Non Navigant")) collection = "NonNavigant";
                dpr.ajouter("DPR",collection);
                JOptionPane.showMessageDialog(null, "*****  Relation Ajouter  *****");
            }
            else JOptionPane.showMessageDialog(null, "Deja Existe");

        }   catch (UnknownHostException ex) {
            Logger.getLogger(AjoutDPR.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_ajouter1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomActionPerformed

    private void nomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomKeyReleased

    }//GEN-LAST:event_nomKeyReleased

    private void jour1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jour1MouseClicked

    }//GEN-LAST:event_jour1MouseClicked

    private void jour1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jour1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jour1MouseExited

    private void jour1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jour1MouseReleased

    }//GEN-LAST:event_jour1MouseReleased

    private void jour1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jour1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jour1ActionPerformed

    private void jour1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jour1KeyReleased

    }//GEN-LAST:event_jour1KeyReleased

    private void jour1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jour1KeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE )||jour.getText().length()==2)
        {   getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jour1KeyTyped

    private void prenomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prenomKeyReleased

    }//GEN-LAST:event_prenomKeyReleased

    private void numTelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numTelKeyReleased

    }//GEN-LAST:event_numTelKeyReleased

    private void numTelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numTelKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE)|| numTel.getText().length()==8)
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_numTelKeyTyped

    private void annee1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_annee1KeyReleased

    }//GEN-LAST:event_annee1KeyReleased

    private void annee1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_annee1KeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE)||annee.getText().length()==4)
        {   getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_annee1KeyTyped

    private void adresseKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adresseKeyReleased

    }//GEN-LAST:event_adresseKeyReleased

    private void listPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listPPActionPerformed
        try {
            listP.removeAllItems();
            chargerListPersonne();
            chargerListDepart();
            chargerTout();

        } catch (UnknownHostException ex) {
            Logger.getLogger(AjoutDPR.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_listPPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(qqqqq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(qqqqq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(qqqqq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(qqqqq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new qqqqq().setVisible(true);
                } catch (UnknownHostException ex) {
                    Logger.getLogger(qqqqq.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adresse;
    private AjoutRelation.AjoutVTR ajoutVTR1;
    private javax.swing.JButton ajouter;
    private javax.swing.JButton ajouter1;
    private javax.swing.JTextField annee;
    private javax.swing.JTextField annee1;
    private javax.swing.JTextField capacite;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jour;
    private javax.swing.JTextField jour1;
    private javax.swing.JComboBox listA;
    private javax.swing.JComboBox listD;
    private javax.swing.JComboBox listD1;
    private javax.swing.JComboBox listP;
    private javax.swing.JComboBox listPP;
    private javax.swing.JTextField mois;
    private javax.swing.JTextField mois1;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField numTel;
    private javax.swing.JTextField prenom;
    private javax.swing.JTextField qc;
    private javax.swing.JTextField type;
    // End of variables declaration//GEN-END:variables
}
