/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GestionRelation;

import Gestion.GestionAvion;
import Listage.Matrix;
import NOSQL.Connexion;
import Vols.Depart;
import Vols.VDR;
import com.mongodb.BasicDBObject;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;
import java.awt.event.KeyEvent;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Ben Abdallah Youssef
 */
public class GestionVDR extends javax.swing.JFrame {

    /**
     * Creates new form pp
     */
    
  
    public GestionVDR() {
        initComponents();
        afficheVD(1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jTextField1 = new javax.swing.JTextField();
        numVVD = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        distanceVD = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        frequenceVD = new javax.swing.JTextField();
        jourVD = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        anneeVD = new javax.swing.JTextField();
        moisVD = new javax.swing.JTextField();
        numDVD = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        anyVD = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableVD = new javax.swing.JTable();
        supprimer = new javax.swing.JButton();
        ajouter1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TUNISAIR");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        // Code of sub-components - not shown here
        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Tunisair_logo.png")));
        jLabel1.setOpaque(true);

        jDesktopPane1.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(204, 204, 255));
        jTextField1.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        jTextField1.setText("Gestion Vol Depart Relation");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        numVVD.setToolTipText("");
        numVVD.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        numVVD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numVVDActionPerformed(evt);
            }
        });
        numVVD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                numVVDKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numVVDKeyTyped(evt);
            }
        });

        jLabel2.setText("Numero Vol");

        jLabel7.setText("Distance");

        distanceVD.setToolTipText("");
        distanceVD.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        distanceVD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                distanceVDActionPerformed(evt);
            }
        });
        distanceVD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                distanceVDKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                distanceVDKeyTyped(evt);
            }
        });

        jLabel8.setText("Fréquence");

        frequenceVD.setToolTipText("");
        frequenceVD.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        frequenceVD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frequenceVDActionPerformed(evt);
            }
        });
        frequenceVD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                frequenceVDKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                frequenceVDKeyTyped(evt);
            }
        });

        jourVD.setToolTipText("Jour");
        jourVD.setName(""); // NOI18N
        jourVD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jourVDMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jourVDMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jourVDMouseReleased(evt);
            }
        });
        jourVD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jourVDActionPerformed(evt);
            }
        });
        jourVD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jourVDKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jourVDKeyTyped(evt);
            }
        });

        jLabel3.setText("Date");

        anneeVD.setToolTipText("Annee");
        anneeVD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                anneeVDKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                anneeVDKeyTyped(evt);
            }
        });

        moisVD.setToolTipText("Mois");
        moisVD.setName(""); // NOI18N
        moisVD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                moisVDMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                moisVDMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                moisVDMouseReleased(evt);
            }
        });
        moisVD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moisVDActionPerformed(evt);
            }
        });
        moisVD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                moisVDKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                moisVDKeyTyped(evt);
            }
        });

        numDVD.setToolTipText("");
        numDVD.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        numDVD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numDVDActionPerformed(evt);
            }
        });
        numDVD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                numDVDKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numDVDKeyTyped(evt);
            }
        });

        jLabel4.setText("Numero Depart");

        jLabel9.setText("Tous");

        anyVD.setToolTipText("");
        anyVD.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        anyVD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anyVDActionPerformed(evt);
            }
        });
        anyVD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                anyVDKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                anyVDKeyTyped(evt);
            }
        });

        jTableVD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableVD);

        supprimer.setText("Supprimer ");
        supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerActionPerformed(evt);
            }
        });

        ajouter1.setText("Annuler");
        ajouter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouter1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(164, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(numVVD, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(distanceVD, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(frequenceVD, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(numDVD, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jourVD, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(moisVD, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(anneeVD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(anyVD))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(supprimer, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(ajouter1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(307, 307, 307))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(frequenceVD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(distanceVD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numVVD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numDVD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jourVD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(moisVD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(anneeVD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(anyVD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(ajouter1)
                        .addGap(18, 18, 18)
                        .addComponent(supprimer))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void afficheJTableVD(Object[][] MyArray)
    {
         jTableVD.setModel(new javax.swing.table.DefaultTableModel(
                        MyArray,
                        new String [] {
                            "Numero Vol", "Distance", "Fréquence", "Numero Depart", "Date"
                        }
                        )
                  {
                            boolean[] canEdit = new boolean [] {
                            false, false, false, false, false
                        };
                        @Override
                        public boolean isCellEditable(int rowIndex, int columnIndex) {
                            return canEdit [columnIndex];
                        }
                    }
         );
    }
    
    private boolean testVD(DBObject object, int n)
    {
           String C[][]=new String[7][2];
   C[0][0]="numV";C[0][1]=numVVD.getText();
   C[1][0]="distance";C[1][1]=distanceVD.getText();
   C[2][0]="frequence";C[2][1]=frequenceVD.getText();   
   C[3][0]="numD";C[3][1]=numDVD.getText();
   C[4][0]="jour";C[4][1]=jourVD.getText();
   C[5][0]="mois";C[5][1]=moisVD.getText();
   C[6][0]="annee";C[6][1]=anneeVD.getText();
   int i=0;
   boolean ok;
        if(n==1)
        {
            ok=true;
            while(ok&&i<7)
            {
         ok = object.get(C[i][0]).toString().toUpperCase().contains(C[i][1].toUpperCase());         
         i++;
            }}        
         else 
        {
            ok=false;
             while(i<7)
            {
        ok = ok || object.get(C[i][0]).toString().toUpperCase().contains(anyVD.getText().toUpperCase());         
         i++;
            }
        }
        return ok;
    }
   
    
    private void afficheVD(int e)
{
        try {
            Connexion connexion = new Connexion("Airport");
             DBCursor listAvion = connexion.getListe("VDR");   
             int i=0;
             Object[][] tab = new Object[listAvion.count()][5];             
             while (listAvion.hasNext())
             {
                 DBObject object = listAvion.next();
                 if(testVD(object,e))   
                 {                   
                       tab[i][0]=object.get("numV");
                       tab[i][1]=object.get("distance");
                       tab[i][2]=object.get("frequence");
                       tab[i][3]=object.get("numD").toString().toUpperCase();                       
                       tab[i][4]=object.get("jour")+"/"+object.get("mois")+"/"+object.get("annee");
                      i++;
                 }
             }                                          
             Object[][] MyArray = new Object[i][5];
             for(int j=0;j<i;j++)
             {
                System.arraycopy(tab[j], 0, MyArray[j], 0, 5);
             }            
         
       afficheJTableVD(MyArray);
    
        } catch (UnknownHostException ex) {
            Logger.getLogger(GestionAvion.class.getName()).log(Level.SEVERE, null, ex);        
        }
   
}
   
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void numVVDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numVVDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numVVDActionPerformed

    private void numVVDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numVVDKeyReleased
        afficheVD(1);        // TODO add your handling code here:
    }//GEN-LAST:event_numVVDKeyReleased

    private void numVVDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numVVDKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE)|| numVVD.getText().length()==8)
        {   getToolkit().beep();
            evt.consume();
        }

    }//GEN-LAST:event_numVVDKeyTyped

    private void distanceVDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_distanceVDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_distanceVDActionPerformed

    private void distanceVDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_distanceVDKeyReleased
        afficheVD(1);        // TODO add your handling code here:
    }//GEN-LAST:event_distanceVDKeyReleased

    private void distanceVDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_distanceVDKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE))
        {   getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_distanceVDKeyTyped

    private void frequenceVDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frequenceVDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_frequenceVDActionPerformed

    private void frequenceVDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_frequenceVDKeyReleased
        afficheVD(1);        // TODO add your handling code here:
    }//GEN-LAST:event_frequenceVDKeyReleased

    private void frequenceVDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_frequenceVDKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE))
        {   getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_frequenceVDKeyTyped

    private void jourVDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jourVDMouseClicked

    }//GEN-LAST:event_jourVDMouseClicked

    private void jourVDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jourVDMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jourVDMouseExited

    private void jourVDMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jourVDMouseReleased

    }//GEN-LAST:event_jourVDMouseReleased

    private void jourVDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jourVDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jourVDActionPerformed

    private void jourVDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jourVDKeyReleased
        afficheVD(1);
    }//GEN-LAST:event_jourVDKeyReleased

    private void jourVDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jourVDKeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE )||jourVD.getText().length()==2)
        {   getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jourVDKeyTyped

    private void anneeVDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_anneeVDKeyReleased
        afficheVD(1);
    }//GEN-LAST:event_anneeVDKeyReleased

    private void anneeVDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_anneeVDKeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE)||anneeVD.getText().length()==4)
        {   getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_anneeVDKeyTyped

    private void moisVDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moisVDMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_moisVDMouseClicked

    private void moisVDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moisVDMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_moisVDMouseExited

    private void moisVDMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moisVDMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_moisVDMouseReleased

    private void moisVDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moisVDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moisVDActionPerformed

    private void moisVDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_moisVDKeyReleased
        afficheVD(1);
    }//GEN-LAST:event_moisVDKeyReleased

    private void moisVDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_moisVDKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE )||moisVD.getText().length()==2)
        {   getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_moisVDKeyTyped

    private void numDVDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numDVDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numDVDActionPerformed

    private void numDVDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numDVDKeyReleased
        afficheVD(1);
    }//GEN-LAST:event_numDVDKeyReleased

    private void numDVDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numDVDKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE)|| numVVD.getText().length()==8)
        {   getToolkit().beep();
            evt.consume();
        }

    }//GEN-LAST:event_numDVDKeyTyped

    private void anyVDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anyVDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anyVDActionPerformed

    private void anyVDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_anyVDKeyReleased
        if(anyVD.getText().length()==0)
        afficheVD(1);
        else
             afficheVD(2);
    }//GEN-LAST:event_anyVDKeyReleased

    private void anyVDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_anyVDKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_anyVDKeyTyped

    private void supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerActionPerformed
        if(jTableVD.getSelectedRow()<0)
        {
            JOptionPane.showMessageDialog(null, "*****  Selectionner Une Relation  *****");
        }
        else
            {
            VDR p = new VDR(new Depart(jTableVD.getValueAt(jTableVD.getSelectedRow(), 3).toString()));
            try {
                p.supprimerDepart("VDR");
                
        afficheVD(1);
            } catch (UnknownHostException ex) {
                Logger.getLogger(GestionVDR.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
       
    }//GEN-LAST:event_supprimerActionPerformed

    private void ajouter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouter1ActionPerformed
        numVVD.setText("");
        numDVD.setText("");
        jourVD.setText(""); moisVD.setText("");
        anneeVD.setText("");
        frequenceVD.setText("");
        distanceVD.setText("");
        anyVD.setText("");
        afficheVD(1);// TODO add your handling code here:
    }//GEN-LAST:event_ajouter1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionVDR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouter1;
    private javax.swing.JTextField anneeVD;
    private javax.swing.JTextField anyVD;
    private javax.swing.JTextField distanceVD;
    private javax.swing.JTextField frequenceVD;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableVD;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jourVD;
    private javax.swing.JTextField moisVD;
    private javax.swing.JTextField numDVD;
    private javax.swing.JTextField numVVD;
    private javax.swing.JButton supprimer;
    // End of variables declaration//GEN-END:variables
}
