/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GestionRelation;

import Gestion.GestionAvion;
import Listage.Matrix;
import NOSQL.Connexion;
import Vols.DPR;
import Vols.Depart;
import com.mongodb.BasicDBObject;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;
import java.awt.event.KeyEvent;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author Ben Abdallah Youssef
 */
public class GestionDPR extends javax.swing.JFrame {

    /**
     * Creates new form pp
     */
    
  
    public GestionDPR() {
        initComponents();
        afficheDPR(1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        num = new javax.swing.JTextField();
        nom = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        any = new javax.swing.JTextField();
        prenom = new javax.swing.JTextField();
        numTel = new javax.swing.JTextField();
        list = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        adresse = new javax.swing.JTextField();
        jour1 = new javax.swing.JTextField();
        numD = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        annee = new javax.swing.JTextField();
        mois = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        ajouter1 = new javax.swing.JButton();
        supprimer2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TUNISAIR");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        // Code of sub-components - not shown here
        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Tunisair_logo.png")));
        jLabel1.setOpaque(true);

        jDesktopPane1.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(204, 204, 255));
        jTextField1.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        jTextField1.setText("Gestion Depart Personne Relation");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Prenom");

        jLabel5.setText("Num TEL");

        jLabel6.setText("Adresse");

        num.setToolTipText("");
        num.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numActionPerformed(evt);
            }
        });
        num.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                numKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numKeyTyped(evt);
            }
        });

        nom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nomKeyReleased(evt);
            }
        });

        jLabel2.setText("Numero CIN");

        jLabel7.setText("Tous");

        any.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                anyKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                anyKeyTyped(evt);
            }
        });

        prenom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                prenomKeyReleased(evt);
            }
        });

        numTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                numTelKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numTelKeyTyped(evt);
            }
        });

        list.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Passager", "Navigant", "Non Navigant", "Personnel", "Pilote", "Tous" }));
        list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listActionPerformed(evt);
            }
        });

        jLabel3.setText("Nom");

        adresse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                adresseKeyReleased(evt);
            }
        });

        jour1.setToolTipText("Jour");
        jour1.setName(""); // NOI18N
        jour1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jour1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jour1MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jour1MouseReleased(evt);
            }
        });
        jour1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jour1ActionPerformed(evt);
            }
        });
        jour1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jour1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jour1KeyTyped(evt);
            }
        });

        numD.setToolTipText("");
        numD.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        numD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numDActionPerformed(evt);
            }
        });
        numD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                numDKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numDKeyTyped(evt);
            }
        });

        jLabel8.setText("Date");

        jLabel9.setText("Numero Depart");

        annee.setToolTipText("Annee");
        annee.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                anneeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                anneeKeyTyped(evt);
            }
        });

        mois.setToolTipText("Mois");
        mois.setName(""); // NOI18N
        mois.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                moisMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                moisMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                moisMouseReleased(evt);
            }
        });
        mois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moisActionPerformed(evt);
            }
        });
        mois.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                moisKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                moisKeyTyped(evt);
            }
        });

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero Depart", "Jour", "Mois", "Année", "Type", "N° CIN", "Nom", "Prénom", "Adresse", "N° TEL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable);

        ajouter1.setText("Annuler");
        ajouter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouter1ActionPerformed(evt);
            }
        });

        supprimer2.setText("Supprimer ");
        supprimer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimer2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(145, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(num, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numD, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(prenom, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(adresse, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(numTel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(list, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(191, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jour1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(mois, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(annee, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(any, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(supprimer2)
                                        .addGap(18, 18, 18)
                                        .addComponent(ajouter1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jour1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(annee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(any, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(supprimer2)
                    .addComponent(ajouter1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(177, 177, 177))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void afficheJTablePD(Object[][] MyArray)
    {
         jTable.setModel(new javax.swing.table.DefaultTableModel(
                        MyArray,
                        new String [] {
                              "Numero Depart", "Date", "Type",
                            "N° CIN", "Nom", "Prénom", "Adresse", "N° Tel"
                        }
                        )
                  {
                            boolean[] canEdit = new boolean [] {
                            false, false, false, false, false, false, false, false, false, false
                        };
                        @Override
                        public boolean isCellEditable(int rowIndex, int columnIndex) {
                            return canEdit [columnIndex];
                        }
                    }
         );
    }
    
    private boolean testPD(DBObject object, int n)
    {
        String C[][]=new String[10][2];
   C[0][0]="numD";C[0][1]=numD.getText();
   C[1][0]="jour";C[1][1]=jour1.getText();
   C[2][0]="mois";C[2][1]=mois.getText();
   C[3][0]="annee";C[3][1]=annee.getText();
   String Type = list.getSelectedItem().toString();
   if (Type.equals("Non Navigant"))
       Type = "NonNavigant";
   C[4][0]="type";C[4][1]=Type;
   C[5][0]="numCIN";C[5][1]=num.getText();
   C[6][0]="nom";C[6][1]=nom.getText();
   C[7][0]="prenom";C[7][1]=prenom.getText();   
   C[8][0]="adresse";C[8][1]=adresse.getText();
   C[9][0]="numTel";C[9][1]=numTel.getText();
   int i=0;
   boolean ok;
        if(n==1)
        {ok=true;
            while(ok&&i<10)
            {
         ok = object.get(C[i][0]).toString().toUpperCase().contains(C[i][1].toUpperCase());
         
         i++;
            }}
        else if(n==2)
        {ok=false;
         if(object.get(C[4][0]).toString().toUpperCase().equals(C[4][1].toUpperCase()))
             while(i<10)
           {        
         ok = ok || object.get(C[i][0]).toString().toUpperCase().contains(any.getText().toUpperCase());         
         i++;         
         if(i==4)i++;
            }
        }
        else if(n==3)
        {
            ok=true;
             while(ok&&i<10)
            {
         ok = object.get(C[i][0]).toString().toUpperCase().contains(C[i][1].toUpperCase());
         i++;
         if(i==4)i++;
            }
        }
         else 
        {
            ok=false;
             while(i<10)
            {
        ok = ok || object.get(C[i][0]).toString().toUpperCase().contains(any.getText().toUpperCase());         
         i++;
         if(i==4)i++;
            }
        }
        return ok;
    }
   
    
    private void afficheDPR(int e)
{
        try {
            Connexion connexion = new Connexion("Airport");
             DBCursor listAvion = connexion.getListe("DPR");
             String Type = list.getSelectedItem().toString();
   if (Type.equals("Non Navigant"))
       Type = "NonNavigant";
   if((list.getSelectedItem().toString().equals("Tous"))&&(e==2))
       e=4;
   if((list.getSelectedItem().toString().equals("Tous"))&&(e==1))
       e=3;
   
             int i=0;
             Object[][] tab = new Object[listAvion.count()][8];             
             while (listAvion.hasNext())
             {
                 DBObject object = listAvion.next();
                 if(testPD(object,e))                    
                 
                 {                   
                       tab[i][0]=object.get("numD");
                       tab[i][1]=object.get("jour")+"/"+object.get("mois")+"/"+object.get("annee");
                       tab[i][2]=object.get("type").toString().toUpperCase();
                       tab[i][3]=object.get("numCIN");
                       tab[i][4]=object.get("nom").toString().toUpperCase();
                       tab[i][5]=object.get("prenom").toString().toUpperCase();
                       tab[i][6]=object.get("adresse").toString().toUpperCase();
                       tab[i][7]=object.get("numTel");
                      i++;
                 }
             }                                          
             Object[][] MyArray = new Object[i][8];
             for(int j=0;j<i;j++)
             {
                System.arraycopy(tab[j], 0, MyArray[j], 0, 8);
             }            
         
       afficheJTablePD(MyArray);
    
        } catch (UnknownHostException ex) {
            Logger.getLogger(GestionAvion.class.getName()).log(Level.SEVERE, null, ex);        
        }
   
}
    
    
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void numActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numActionPerformed

    private void numKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numKeyReleased
        afficheDPR(1);
    }//GEN-LAST:event_numKeyReleased

    private void numKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE)|| num.getText().length()==8)
        {   getToolkit().beep();
            evt.consume();
        }

    }//GEN-LAST:event_numKeyTyped

    private void nomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomKeyReleased
        afficheDPR(1);        // TODO add your handling code here:
    }//GEN-LAST:event_nomKeyReleased

    private void anyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_anyKeyReleased
        if(any.getText().length()==0)afficheDPR(1);
        else
            afficheDPR(2);   // TODO add your handling code here:
    }//GEN-LAST:event_anyKeyReleased

    private void anyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_anyKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_anyKeyTyped

    private void prenomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prenomKeyReleased
        afficheDPR(1);        // TODO add your handling code here:
    }//GEN-LAST:event_prenomKeyReleased

    private void numTelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numTelKeyReleased
        afficheDPR(1);        // TODO add your handling code here:
    }//GEN-LAST:event_numTelKeyReleased

    private void numTelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numTelKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE)|| numTel.getText().length()==8)
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_numTelKeyTyped

    private void listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listActionPerformed
        if(any.getText().length()==0)
        afficheDPR(1);
        else afficheDPR(2);   
    }//GEN-LAST:event_listActionPerformed

    private void adresseKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adresseKeyReleased
        afficheDPR(1);        // TODO add your handling code here:
    }//GEN-LAST:event_adresseKeyReleased

    private void jour1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jour1MouseClicked

    }//GEN-LAST:event_jour1MouseClicked

    private void jour1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jour1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jour1MouseExited

    private void jour1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jour1MouseReleased

    }//GEN-LAST:event_jour1MouseReleased

    private void jour1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jour1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jour1ActionPerformed

    private void jour1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jour1KeyReleased
        afficheDPR(1);
    }//GEN-LAST:event_jour1KeyReleased

    private void jour1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jour1KeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE )||jour1.getText().length()==2)
        {   getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jour1KeyTyped

    private void numDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numDActionPerformed

    private void numDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numDKeyReleased
        afficheDPR(1);        // TODO add your handling code here:
    }//GEN-LAST:event_numDKeyReleased

    private void numDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numDKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE)|| numD.getText().length()==8)
        {   getToolkit().beep();
            evt.consume();
        }

    }//GEN-LAST:event_numDKeyTyped

    private void anneeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_anneeKeyReleased
        afficheDPR(1);
    }//GEN-LAST:event_anneeKeyReleased

    private void anneeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_anneeKeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE)||annee.getText().length()==4)
        {   getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_anneeKeyTyped

    private void moisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moisMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_moisMouseClicked

    private void moisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moisMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_moisMouseExited

    private void moisMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moisMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_moisMouseReleased

    private void moisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moisActionPerformed

    private void moisKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_moisKeyReleased
        afficheDPR(1);
    }//GEN-LAST:event_moisKeyReleased

    private void moisKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_moisKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE )||mois.getText().length()==2)
        {   getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_moisKeyTyped

    private void ajouter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouter1ActionPerformed
        num.setText("");
        numD.setText("");
        jour1.setText(""); mois.setText("");
        annee.setText("");
        nom.setText("");
        prenom.setText("");
        adresse.setText("");
        any.setText("");
        numTel.setText("");
        afficheDPR(1);// TODO add your handling code here:
    }//GEN-LAST:event_ajouter1ActionPerformed

    private void supprimer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimer2ActionPerformed
        if(jTable.getSelectedRow()<0)
        {
            JOptionPane.showMessageDialog(null, "*****  Selectionner Une Seule Relation  *****");
        }
        else
            {
                String type =jTable.getValueAt(jTable.getSelectedRow(), 4).toString();
if(type.equals("NAVIGANT"))
    type="Navigant";
else if(type.equals("NONNAVIGANT"))
    type="NonNavigant";
if(type.equals("PILOTE"))
    type="Pilote";
if(type.equals("PERSONNEL"))
    type="Personnel";
if(type.equals("PASSAGER"))
    type="Passager";
                 DPR dpr = new DPR(new Depart(jTable.getValueAt(jTable.getSelectedRow(), 0).toString()),
                type);
                try {
                    dpr.supprimerDepart("DPR");
                } catch (UnknownHostException ex) {
                    Logger.getLogger(GestionDAR.class.getName()).log(Level.SEVERE, null, ex);
                }
            
        num.setText("");
        numD.setText("");
        jour1.setText(""); mois.setText("");
        annee.setText("");
        nom.setText("");
        prenom.setText("");
        adresse.setText("");
        any.setText("");
        numTel.setText("");
        afficheDPR(1);
        }
    }//GEN-LAST:event_supprimer2ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionDPR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adresse;
    private javax.swing.JButton ajouter1;
    private javax.swing.JTextField annee;
    private javax.swing.JTextField any;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jour1;
    private javax.swing.JComboBox list;
    private javax.swing.JTextField mois;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField num;
    private javax.swing.JTextField numD;
    private javax.swing.JTextField numTel;
    private javax.swing.JTextField prenom;
    private javax.swing.JButton supprimer2;
    // End of variables declaration//GEN-END:variables
}
