/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Autre;

import Listage.List;
import NOSQL.Connexion;
import Vols.Avion;
import Vols.DAR;
import Vols.Depart;
import com.mongodb.BasicDBObject;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;
import java.awt.event.KeyEvent;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Ben Abdallah Youssef
 */
public class AjoutDAR extends javax.swing.JFrame {

    /**
     * Creates new form pp
     */
    
  
    public AjoutDAR() throws UnknownHostException {
        initComponents();
        chargerListAvion();
        chargerListDepart();
        chargerTout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ajouter = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        qc = new javax.swing.JTextField();
        listA = new javax.swing.JComboBox();
        listD = new javax.swing.JComboBox();
        type = new javax.swing.JTextField();
        capacite = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jour = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        annee = new javax.swing.JTextField();
        mois = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TUNISAIR");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        // Code of sub-components - not shown here
        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Tunisair_logo.png")));
        jLabel1.setOpaque(true);

        ajouter.setText("Ajouter");
        ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterActionPerformed(evt);
            }
        });

        jLabel2.setText("Numero Depart");

        jLabel3.setText("Numero Avion");

        jDesktopPane1.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(204, 204, 255));
        jTextField1.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        jTextField1.setText("Ajout Depart Avion Relation");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Quantite Carburant");

        qc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qcKeyTyped(evt);
            }
        });

        listA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listAActionPerformed(evt);
            }
        });

        listD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listDActionPerformed(evt);
            }
        });

        type.setEnabled(false);
        type.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                typeKeyReleased(evt);
            }
        });

        capacite.setEnabled(false);
        capacite.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                capaciteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                capaciteKeyTyped(evt);
            }
        });

        jLabel6.setText("Type");

        jLabel7.setText("Capacité");

        jour.setToolTipText("Jour");
        jour.setEnabled(false);
        jour.setName(""); // NOI18N
        jour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jourMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jourMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jourMouseReleased(evt);
            }
        });
        jour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jourActionPerformed(evt);
            }
        });
        jour.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jourKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jourKeyTyped(evt);
            }
        });

        jLabel5.setText("Date");

        annee.setToolTipText("Annee");
        annee.setEnabled(false);
        annee.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                anneeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                anneeKeyTyped(evt);
            }
        });

        mois.setToolTipText("Mois");
        mois.setEnabled(false);
        mois.setName(""); // NOI18N
        mois.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                moisMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                moisMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                moisMouseReleased(evt);
            }
        });
        mois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moisActionPerformed(evt);
            }
        });
        mois.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                moisKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                moisKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jDesktopPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(qc, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(285, 285, 285))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(listD, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jour, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(mois, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(annee, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(listA, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(capacite)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ajouter)
                        .addGap(352, 352, 352))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(capacite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(listA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(listD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(annee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(ajouter)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterActionPerformed
        
        
        if(qc.getText().length()==0)
        {
             JOptionPane.showMessageDialog(null, "*****  Saisir Le Quantite De Carburant  *****");
             
        } else
        {
        try {
            //boolean r=true;
            Avion A = new Avion(listA.getSelectedItem().toString());
            Depart D = new Depart(listD.getSelectedItem().toString());
          
         DAR dar = new DAR(D,A,qc.getText().toUpperCase());
            if (dar.rechercheDepart("DAR"))
            {                
            dar.ajouter("DAR");
            JOptionPane.showMessageDialog(null, "*****  Relation Ajouter  *****");
            qc.setText("");
            }
            else JOptionPane.showMessageDialog(null, "Deja Existe");
        
        }   catch (UnknownHostException ex) {
                Logger.getLogger(AjoutDAR.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_ajouterActionPerformed

    
    void chargerListAvion() throws UnknownHostException
    {
    Connexion connexion = new Connexion("Airport");
    DBCursor list = connexion.getListe("Avion");
    List l =  new List(list.count());
    String listAvion[]=l.remplirByNum(list);
    for(int i=0;i<listAvion.length;i++)
    listA.addItem(listAvion[i]);
    
    }
    
    void chargerListDepart() throws UnknownHostException
    {
    Connexion connexion = new Connexion("Airport");
    DBCursor list = connexion.getListe("Depart");
    List l =  new List(list.count());
    String listAvion[]=l.remplirByNum(list);
    for(int i=0;i<listAvion.length;i++)
    listD.addItem(listAvion[i]);    
    }
    
    void chargerTout() throws UnknownHostException
    {
    Connexion connexion = new Connexion("Airport");
    if(listA.getSelectedIndex()>=0)
    {
    DBCursor list = connexion.findListe("Avion",new BasicDBObject().append("num",listA.getSelectedItem().toString()));
    DBObject object = list.next();
    type.setText(object.get("type").toString());
    capacite.setText(object.get("capacite").toString());
    }
    if(listD.getSelectedIndex()>=0)
    {
    DBCursor list = connexion.findListe("Depart",new BasicDBObject().append("num",listD.getSelectedItem().toString()));
    DBObject object = list.next();
    jour.setText(object.get("jour").toString());
    mois.setText(object.get("mois").toString());
    annee.setText(object.get("annee").toString());
    }
    }
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void qcKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qcKeyTyped
        // TODO add your handling code here:
         char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE)|| qc.getText().length()==5)
        {   getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_qcKeyTyped

    private void listAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listAActionPerformed
        try {
            chargerTout();        // TODO add your handling code here:
        } catch (UnknownHostException ex) {
            Logger.getLogger(AjoutDAR.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_listAActionPerformed

    private void typeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_typeKeyReleased
             // TODO add your handling code here:
    }//GEN-LAST:event_typeKeyReleased

    private void capaciteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_capaciteKeyReleased
     
    }//GEN-LAST:event_capaciteKeyReleased

    private void capaciteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_capaciteKeyTyped
        
    }//GEN-LAST:event_capaciteKeyTyped

    private void jourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jourMouseClicked

    }//GEN-LAST:event_jourMouseClicked

    private void jourMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jourMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jourMouseExited

    private void jourMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jourMouseReleased

    }//GEN-LAST:event_jourMouseReleased

    private void jourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jourActionPerformed

    private void jourKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jourKeyReleased
       
    }//GEN-LAST:event_jourKeyReleased

    private void jourKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jourKeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE )||jour.getText().length()==2)
        {   getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jourKeyTyped

    private void anneeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_anneeKeyReleased

    }//GEN-LAST:event_anneeKeyReleased

    private void anneeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_anneeKeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE)||annee.getText().length()==4)
        {   getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_anneeKeyTyped

    private void moisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moisMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_moisMouseClicked

    private void moisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moisMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_moisMouseExited

    private void moisMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moisMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_moisMouseReleased

    private void moisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moisActionPerformed

    private void moisKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_moisKeyReleased

    }//GEN-LAST:event_moisKeyReleased

    private void moisKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_moisKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE )||mois.getText().length()==2)
        {   getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_moisKeyTyped

    private void listDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listDActionPerformed
        try {
            chargerTout();        // TODO add your handling code here:
        } catch (UnknownHostException ex) {
            Logger.getLogger(AjoutDAR.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_listDActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjoutDAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjoutDAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjoutDAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjoutDAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AjoutDAR().setVisible(true);
                } catch (UnknownHostException ex) {
                    Logger.getLogger(AjoutDAR.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouter;
    private javax.swing.JTextField annee;
    private javax.swing.JTextField capacite;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jour;
    private javax.swing.JComboBox listA;
    private javax.swing.JComboBox listD;
    private javax.swing.JTextField mois;
    private javax.swing.JTextField qc;
    private javax.swing.JTextField type;
    // End of variables declaration//GEN-END:variables
}
