/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gestion;


import NOSQL.Connexion;
import Vols.Troncon;
import Vols.VTR;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;
import java.awt.event.KeyEvent;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Ben Abdallah Youssef
 */
public class GestionTroncon extends javax.swing.JFrame {

    /**
     * Creates new form pp
     */
    
  
    public GestionTroncon() {
        initComponents();
        afficheT(2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        numTT = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jTextField1 = new javax.swing.JTextField();
        villeDT = new javax.swing.JTextField();
        villeAT = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        anyT = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableT = new javax.swing.JTable();
        ajouter = new javax.swing.JButton();
        ajouter1 = new javax.swing.JButton();
        supprimer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TUNISAIR");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        // Code of sub-components - not shown here
        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Tunisair_logo.png")));
        jLabel1.setOpaque(true);

        numTT.setToolTipText("");
        numTT.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        numTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numTTActionPerformed(evt);
            }
        });
        numTT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                numTTKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numTTKeyTyped(evt);
            }
        });

        jLabel2.setText("Numero");

        jDesktopPane1.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(204, 204, 255));
        jTextField1.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        jTextField1.setText("Gestion Troncon");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        villeDT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                villeDTKeyReleased(evt);
            }
        });

        villeAT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                villeATKeyReleased(evt);
            }
        });

        jLabel3.setText("Ville de Depart");

        jLabel4.setText("Ville d'Arrivée");

        anyT.setToolTipText("");
        anyT.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        anyT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anyTActionPerformed(evt);
            }
        });
        anyT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                anyTKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                anyTKeyTyped(evt);
            }
        });

        jLabel5.setText("Tous");

        jTableT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero", "Ville de Depart", "Ville d'Arrivée"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableT);

        ajouter.setText("Ajouter");
        ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterActionPerformed(evt);
            }
        });

        ajouter1.setText("Annuler");
        ajouter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouter1ActionPerformed(evt);
            }
        });

        supprimer.setText("Supprimer");
        supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(numTT, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(villeDT, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(villeAT, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(anyT, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(supprimer)
                            .addComponent(ajouter1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(289, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(villeDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(villeAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(anyT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ajouter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(supprimer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ajouter1)))
                .addContainerGap(202, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     private void afficheJTableT(Object[][] MyArray)
    {
         jTableT.setModel(new javax.swing.table.DefaultTableModel(
                        MyArray,
                        new String [] {
                             "Numero", "Ville de Depart", "Ville d'Arrivée"
                        }
                        )
                  {
                                               boolean[] canEdit = new boolean [] {
                            false, false, false
                        };
                        @Override
                        public boolean isCellEditable(int rowIndex, int columnIndex) {
                            return canEdit [columnIndex];
                        }
                    }
         );
    }
    
    private boolean testT(DBObject object, int i)
    {
        if(i==1)
        return object.get("num").toString().toUpperCase().contains(numTT.getText().toUpperCase())
                         &&object.get("villeDepart").toString().toUpperCase().contains(villeDT.getText().toUpperCase())
                         &&object.get("villeArrive").toString().toUpperCase().contains(villeAT.getText().toUpperCase());
        else return
                object.get("num").toString().contains(anyT.getText().toUpperCase())
                         ||object.get("villeDepart").toString().toUpperCase().contains(anyT.getText().toUpperCase())
                         ||object.get("villeArrive").toString().toUpperCase().contains(anyT.getText().toUpperCase());
    }
   
    
    private void afficheT(int e)
{
        try {
            Connexion connexion = new Connexion("Airport");
             DBCursor listTroncon = connexion.getListe("Troncon");
             int i=0;
             Object[][] tab = new Object[listTroncon.count()][3];             
             while (listTroncon.hasNext())
             {
                 DBObject object = listTroncon.next();
                 if(testT(object,e))                    
                 
                 {                    
                     tab[i][0]=object.get("num");
                     tab[i][1]=object.get("villeDepart");
                     tab[i][2]=object.get("villeArrive");
                      i++;
                 }
             }                             
             
             Object[][] MyArray = new Object[i][3];
             for(int j=0;j<i;j++)
             {
                 MyArray[j][0]=tab[j][0];
                    MyArray[j][1]=tab[j][1];
                       MyArray[j][2]=tab[j][2];
             }            
         
       afficheJTableT(MyArray);
        } catch (UnknownHostException ex) {
            Logger.getLogger(GestionAvion.class.getName()).log(Level.SEVERE, null, ex);        
        }
   
}

    private void numTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numTTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numTTActionPerformed

    private void numTTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numTTKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE)|| numTT.getText().length()==8)
        {   getToolkit().beep();
            evt.consume();
        }
        
    }//GEN-LAST:event_numTTKeyTyped

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void anyTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anyTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anyTActionPerformed

    private void anyTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_anyTKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_anyTKeyTyped

    private void numTTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numTTKeyReleased
afficheT(1);        // TODO add your handling code here:
    }//GEN-LAST:event_numTTKeyReleased

    private void villeDTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_villeDTKeyReleased
afficheT(1);        // TODO add your handling code here:
    }//GEN-LAST:event_villeDTKeyReleased

    private void villeATKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_villeATKeyReleased
afficheT(1);        // TODO add your handling code here:
    }//GEN-LAST:event_villeATKeyReleased

    private void anyTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_anyTKeyReleased
 
     afficheT(2);
 
    }//GEN-LAST:event_anyTKeyReleased

    private void ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterActionPerformed
        // TODO add your handling code here:

        if(numTT.getText().length()==0)
        {
            JOptionPane.showMessageDialog(null, "*****  Saisair Le Numero  *****");

        }else if(villeDT.getText().length()==0)
        {
            JOptionPane.showMessageDialog(null, "*****  Saisir La Ville De Depart  *****");
        }else if(villeAT.getText().length()==0)
        {
            JOptionPane.showMessageDialog(null, "*****  Saisir La Ville De Depart  *****");
        }
        else
        {
            Troncon v = new Troncon(numTT.getText(),villeDT.getText().toUpperCase(),villeAT.getText().toUpperCase());
            try {
                if (v.recherche("Troncon"))
                {
                    v.ajouter("Troncon");
                    numTT.setText(""); anyT.setText("");
        villeDT.setText("");
        villeAT.setText("");
        afficheT(1);
                }
                else JOptionPane.showMessageDialog(null, "Deja Existe");
            } catch (UnknownHostException ex) {
                Logger.getLogger(GestionTroncon.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
       

    }//GEN-LAST:event_ajouterActionPerformed

    private void ajouter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouter1ActionPerformed
        numTT.setText("");
        villeAT.setText(""); villeDT.setText("");
        anyT.setText("");
        afficheT(1);// TODO add your handling code here:
    }//GEN-LAST:event_ajouter1ActionPerformed

    private void supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerActionPerformed
if(jTableT.getSelectedRow()<0)
        {
            JOptionPane.showMessageDialog(null, "*****  Selectionner Une Troncon  *****");
        }
else{
    try {
             Troncon v = new Troncon(jTableT.getValueAt(jTableT.getSelectedRow(), 0).toString());
              VTR vtr = new VTR(new Troncon(jTableT.getValueAt(jTableT.getSelectedRow(), 0).toString()));
                v.supprimer("Troncon");
                vtr.supprimerTroncon("VTR");
            } catch (UnknownHostException ex) {
                Logger.getLogger(GestionDepart.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        numTT.setText("");
        villeAT.setText(""); villeDT.setText(""); anyT.setText("");
        afficheT(1);        // TODO add your handling code here:
    }//GEN-LAST:event_supprimerActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionTroncon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouter;
    private javax.swing.JButton ajouter1;
    private javax.swing.JTextField anyT;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableT;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField numTT;
    private javax.swing.JButton supprimer;
    private javax.swing.JTextField villeAT;
    private javax.swing.JTextField villeDT;
    // End of variables declaration//GEN-END:variables
}
