/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gestion;

import Listage.List;
import Listage.Matrix;
import NOSQL.Connexion;
import Personnages.Navigant;
import Personnages.Passager;
import Vols.DPR;
import Vols.Depart;
import com.mongodb.BasicDBObject;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;
import java.awt.event.KeyEvent;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Ben Abdallah Youssef
 */
public class GestionPersonne extends javax.swing.JFrame {

    /**
     * Creates new form pp
     */
    
  
    public GestionPersonne() throws UnknownHostException {
        initComponents();
        affiche(1);
        listD.setVisible(false);
           jour.setVisible(false);
           mois.setVisible(false);
           annee.setVisible(false);
           jLabel8.setVisible(false);
           jLabel9.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        num = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jTextField1 = new javax.swing.JTextField();
        prenom = new javax.swing.JTextField();
        numTel = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        adresse = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        any = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        list = new javax.swing.JComboBox();
        ajouter = new javax.swing.JButton();
        ajouter1 = new javax.swing.JButton();
        supprimer2 = new javax.swing.JButton();
        jour = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        annee = new javax.swing.JTextField();
        mois = new javax.swing.JTextField();
        listD = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TUNISAIR");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        // Code of sub-components - not shown here
        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Tunisair_logo.png")));
        jLabel1.setOpaque(true);

        num.setToolTipText("");
        num.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numActionPerformed(evt);
            }
        });
        num.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                numKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numKeyTyped(evt);
            }
        });

        jLabel2.setText("Numero CIN");

        jDesktopPane1.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(204, 204, 255));
        jTextField1.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        jTextField1.setText("Gestion Personne");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        prenom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                prenomKeyReleased(evt);
            }
        });

        numTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                numTelKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numTelKeyTyped(evt);
            }
        });

        jLabel3.setText("Nom");

        adresse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                adresseKeyReleased(evt);
            }
        });

        jLabel4.setText("Prenom");

        jLabel5.setText("Num TEL");

        jLabel6.setText("Adresse");

        nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomActionPerformed(evt);
            }
        });
        nom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nomKeyReleased(evt);
            }
        });

        jLabel7.setText("Tous");

        any.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                anyKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                anyKeyTyped(evt);
            }
        });

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N° CIN", "Nom", "Prenom", "Adresse", "N° Tel"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable);

        list.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Navigant", "Non Navigant", "Passager", "Personnel", "Pilote", "Tous" }));
        list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listActionPerformed(evt);
            }
        });

        ajouter.setText("Ajouter");
        ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterActionPerformed(evt);
            }
        });

        ajouter1.setText("Annuler");
        ajouter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouter1ActionPerformed(evt);
            }
        });

        supprimer2.setText("Supprimer");
        supprimer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimer2ActionPerformed(evt);
            }
        });

        jour.setToolTipText("Jour");
        jour.setEnabled(false);
        jour.setName(""); // NOI18N
        jour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jourMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jourMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jourMouseReleased(evt);
            }
        });
        jour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jourActionPerformed(evt);
            }
        });
        jour.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jourKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jourKeyTyped(evt);
            }
        });

        jLabel8.setText("Date");

        annee.setToolTipText("Annee");
        annee.setEnabled(false);
        annee.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                anneeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                anneeKeyTyped(evt);
            }
        });

        mois.setToolTipText("Mois");
        mois.setEnabled(false);
        mois.setName(""); // NOI18N
        mois.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                moisMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                moisMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                moisMouseReleased(evt);
            }
        });
        mois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moisActionPerformed(evt);
            }
        });
        mois.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                moisKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                moisKeyTyped(evt);
            }
        });

        listD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listDActionPerformed(evt);
            }
        });

        jLabel9.setText("Numero Depart");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(list, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(listD, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jour, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mois, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(annee, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ajouter1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(supprimer2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(num, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(prenom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(67, 67, 67)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(adresse, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(numTel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(any, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 833, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(259, 259, 259))
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(listD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ajouter)
                            .addComponent(ajouter1)
                            .addComponent(supprimer2)
                            .addComponent(jour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(annee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(adresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(numTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(any, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
void chargerListDepart() throws UnknownHostException
    {
    Connexion connexion = new Connexion("Airport");
    DBCursor list = connexion.getListe("Depart");
    List l =  new List(list.count());
    String listAvion[]=l.remplirByNum(list);
    for(int i=0;i<listAvion.length;i++)
    listD.addItem(listAvion[i]);    
    }
    
  
  void charger() throws UnknownHostException
    {
    Connexion connexion = new Connexion("Airport");    
    if(listD.getSelectedIndex()>=0)
    {
    DBCursor list = connexion.findListe("Depart",new BasicDBObject().append("num",listD.getSelectedItem().toString()));
     if(list.count()>0)
    {
    DBObject object = list.next();
    jour.setText(object.get("jour").toString());
    mois.setText(object.get("mois").toString());
    annee.setText(object.get("annee").toString());
    }
    }
    }
 
     
   private void afficheJTable(Object[][] MyArray)
    {
         jTable.setModel(new javax.swing.table.DefaultTableModel(
                        MyArray,
                        new String [] {
                           "N° CIN", "Nom", "Prenom", "Adresse", "N° Tel"
                        }
                        )
                  {
                                               boolean[] canEdit = new boolean [] {
                            false, false, false,false,false
                        };
                        @Override
                        public boolean isCellEditable(int rowIndex, int columnIndex) {
                            return canEdit [columnIndex];
                        }
                    }
         );
    }
   private boolean test(DBObject object,int e)
   {
       if(e==1)
       {
   return object.get("cin").toString().contains(num.getText().toUpperCase())
                         &&object.get("nom").toString().toUpperCase().contains(nom.getText().toUpperCase())
                         &&object.get("prenom").toString().toUpperCase().contains(prenom.getText().toUpperCase())
                         &&object.get("adresse").toString().toUpperCase().contains(adresse.getText().toUpperCase())
                          &&object.get("numTel").toString().contains(numTel.getText().toUpperCase());
       }
       else{ return object.get("cin").toString().contains(any.getText().toUpperCase())
                         ||object.get("nom").toString().toUpperCase().contains(any.getText().toUpperCase())
                         ||object.get("prenom").toString().toUpperCase().contains(any.getText().toUpperCase())
                         ||object.get("adresse").toString().toUpperCase().contains(any.getText().toUpperCase())
                          ||object.get("numTel").toString().contains(any.getText().toUpperCase());}
  }
      private void affiche(int e)
{
        try {
            Connexion connexion = new Connexion("Airport");
            String collection=list.getSelectedItem().toString();
  
    if(collection.equals("Non Navigant"))
    collection="NonNavigant"; 
            if(!collection.equals("Tous"))
            {
                
             DBCursor listPersonne = connexion.getListe(collection);             
             Object[][] tab = new Object[listPersonne.count()][5];             
                
    int i=0;
             while (listPersonne.hasNext())
             {
                 DBObject object = listPersonne.next();     
                 if(test(object,e))
                 {                       
                     tab[i][0]=object.get("cin");
                     tab[i][1]=object.get("nom").toString().toUpperCase();
                     tab[i][2]=object.get("prenom").toString().toUpperCase();
                     tab[i][3]=object.get("adresse").toString().toUpperCase();
                     tab[i][4]=object.get("numTel");
                      i++; 
                 }
             }
                                      
             
             Object[][] MyArray = new Object[i][5];
             for(int j=0;j<i;j++)
             {   for(int k=0;k<5;k++)             
                 MyArray[j][k]=tab[j][k];
             } 
       afficheJTable(MyArray);
            }else
            {
                 String Collection[] = new String[]{
            "Navigant","NonNavigant","Passager","Personnel","Pilote"};
                 
               DBCursor list; 
               int tot=0;
          Object all[] = new Object[5];
          int taille[]=new int[5];
                 for(int i=0;i<5;i++)
                 {
          list = connexion.getListe(Collection[i]);
          Object[][] tab = new Object[list.count()][6];
          int j=0;
          while (list.hasNext())
             {
                 DBObject object = list.next();     
                 if(test(object,e))
                 {      
                     tab[j][0]=Collection[i];
                     tab[j][1]=object.get("cin");
                     tab[j][2]=object.get("nom").toString().toUpperCase();
                     tab[j][3]=object.get("prenom").toString().toUpperCase();
                     tab[j][4]=object.get("adresse").toString().toUpperCase();
                     tab[j][5]=object.get("numTel");
                      j++; 
                 }
             }
          tot+=j;
           Object[][] MyArray1 = new Object[j][6];
             for(int l=0;l<j;l++)
             {   System.arraycopy(tab[l], 0, MyArray1[l], 0, 6);
             } 
             all[i]=MyArray1;
             taille[i]=j;
                 }
        Matrix tab = new Matrix(tot,6);
         Object[][] MyArray = null;
          for(int i=0;i<5;i++)
                 {
         MyArray = tab.add((Object[][])all[i],taille[i],6);
                 }
         jTable.setModel(new javax.swing.table.DefaultTableModel(
                 MyArray , 
                        new String [] {
                            "Type","N° CIN", "Nom", "Prenom", "Adresse", "N° Tel"
                        }
                        )
                  {
                            boolean[] canEdit = new boolean [] {
                            false, false, false,false,false,false
                        };
                        @Override
                        public boolean isCellEditable(int rowIndex, int columnIndex) {
                            return canEdit [columnIndex];
                        }
                    }
         );
         
            }
        } catch (UnknownHostException ex) {
            Logger.getLogger(GestionAvion.class.getName()).log(Level.SEVERE, null, ex);        
        }
   
}
  
   
    
    private void numActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numActionPerformed

    private void numKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE)|| num.getText().length()==8)
        {   getToolkit().beep();
            evt.consume();
        }
        
    }//GEN-LAST:event_numKeyTyped

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void numTelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numTelKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE)|| numTel.getText().length()==8)
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_numTelKeyTyped

    private void anyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_anyKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_anyKeyTyped

    private void listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listActionPerformed
if(list.getSelectedItem().equals("Passager"))
        {
           listD.setVisible(true);
           jour.setVisible(true);
           mois.setVisible(true);
           annee.setVisible(true);
           jLabel8.setVisible(true);
           jLabel9.setVisible(true);
           
    try {
        chargerListDepart();
        charger();
    } catch (UnknownHostException ex) {
        Logger.getLogger(GestionPersonne.class.getName()).log(Level.SEVERE, null, ex);
    }
   
        }
else
{
    listD.setVisible(false);
           jour.setVisible(false);
           mois.setVisible(false);
           annee.setVisible(false);
           jLabel8.setVisible(false);
           jLabel9.setVisible(false);
}
if(any.getText().length()>0)
    affiche(2);
else
    affiche(1);

  
    }//GEN-LAST:event_listActionPerformed

    private void numKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numKeyReleased
affiche(1);
    }//GEN-LAST:event_numKeyReleased

    private void anyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_anyKeyReleased
affiche(2);   // TODO add your handling code here:
    }//GEN-LAST:event_anyKeyReleased

    private void nomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomKeyReleased
affiche(1);        // TODO add your handling code here:
    }//GEN-LAST:event_nomKeyReleased

    private void prenomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prenomKeyReleased
affiche(1);        // TODO add your handling code here:
    }//GEN-LAST:event_prenomKeyReleased

    private void adresseKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adresseKeyReleased
affiche(1);        // TODO add your handling code here:
    }//GEN-LAST:event_adresseKeyReleased

    private void numTelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numTelKeyReleased
affiche(1);        // TODO add your handling code here:
    }//GEN-LAST:event_numTelKeyReleased

    private void ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterActionPerformed
        // TODO add your handling code here:

        if(num.getText().length()<8)
        {
            JOptionPane.showMessageDialog(null, "*****  Numero CIN Incorrect  *****");

        }else if(nom.getText().length()==0)
        {
            JOptionPane.showMessageDialog(null, "*****  Saisir Votre Nom  *****");
        }else if(numTel.getText().length()<8)
        {
            JOptionPane.showMessageDialog(null, "*****  Num Tel Incorrect  *****");
        }else if(prenom.getText().length()==0)
        {
            JOptionPane.showMessageDialog(null, "*****  Saisir Votre Prenom  *****");
        }else if(adresse.getText().length()==0)
        {
            JOptionPane.showMessageDialog(null, "*****  Saisir Votre Adresse  *****");
        }

        else
        {
            try {
                Navigant n = new Navigant(num.getText().toUpperCase(),
                        nom.getText().toUpperCase(),prenom.getText().toUpperCase(),
                        adresse.getText().toUpperCase(),numTel.getText().toUpperCase());
                Depart D = new Depart(listD.getSelectedItem().toString());         
                 Passager P = new Passager(num.getText().toUpperCase());
                String collection = list.getSelectedItem().toString();
                 DPR dpr = new DPR(D,P,collection);
            if(collection.equals("Non Navigant"))
        collection="NonNavigant"; 
            if(!collection.equals("Tous"))
            {
                if (n.recherche(collection))
                {
                    
                    n.ajouter(collection);
                    if(collection.equals("Passager"))
                       dpr.ajouter("DPR",collection);
                    
        num.setText("");
        nom.setText("");
        prenom.setText("");
        numTel.setText("");
        adresse.setText("");
        any.setText("");
        affiche(1);
                }
                else JOptionPane.showMessageDialog(null, "Deja Existe");
            }else JOptionPane.showMessageDialog(null, "Choisir Le Type");
            } catch (UnknownHostException ex) {
                Logger.getLogger(GestionPersonne.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_ajouterActionPerformed

    private void nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomActionPerformed

    private void ajouter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouter1ActionPerformed
       num.setText("");
        nom.setText("");
        prenom.setText("");
        numTel.setText("");
        adresse.setText("");
        any.setText("");
        affiche(1);
    }//GEN-LAST:event_ajouter1ActionPerformed

    private void supprimer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimer2ActionPerformed
        // TODO add your handling code here:

       if(jTable.getSelectedRow()<0)
        {
            JOptionPane.showMessageDialog(null, "*****  Selectionner Une Personne  *****");
        }else
        {
            try {
              String collection = list.getSelectedItem().toString();
            if(collection.equals("Non Navigant"))
        collection="NonNavigant"; 
            if(!collection.equals("Tous"))
            {
            Navigant p = new Navigant(jTable.getValueAt(jTable.getSelectedRow(), 0).toString());
            DPR pdr = new DPR(new Passager(jTable.getValueAt(jTable.getSelectedRow(), 0).toString()));
                p.supprimer(collection);
                pdr.supprimerPassager("DPR",collection);
                 
            }
            else 
            {
                Navigant p = new Navigant(jTable.getValueAt(jTable.getSelectedRow(), 1).toString());
                DPR pdr = new DPR(new Passager(jTable.getValueAt(jTable.getSelectedRow(), 1).toString()));
                 p.supprimer(jTable.getValueAt(jTable.getSelectedRow(), 0).toString());
                 pdr.supprimerPassager("DPR",jTable.getValueAt(jTable.getSelectedRow(), 0).toString());
                 
            }
             num.setText("");
        nom.setText("");
        prenom.setText("");
        numTel.setText("");
        adresse.setText("");
        any.setText("");
        affiche(1);
            } catch (UnknownHostException ex) {
                Logger.getLogger(GestionPersonne.class.getName()).log(Level.SEVERE, null, ex);
            }

           
        }
    }//GEN-LAST:event_supprimer2ActionPerformed

    private void jourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jourMouseClicked

    }//GEN-LAST:event_jourMouseClicked

    private void jourMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jourMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jourMouseExited

    private void jourMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jourMouseReleased

    }//GEN-LAST:event_jourMouseReleased

    private void jourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jourActionPerformed

    private void jourKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jourKeyReleased

    }//GEN-LAST:event_jourKeyReleased

    private void jourKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jourKeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE )||jour.getText().length()==2)
        {   getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jourKeyTyped

    private void anneeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_anneeKeyReleased

    }//GEN-LAST:event_anneeKeyReleased

    private void anneeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_anneeKeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE)||annee.getText().length()==4)
        {   getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_anneeKeyTyped

    private void moisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moisMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_moisMouseClicked

    private void moisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moisMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_moisMouseExited

    private void moisMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moisMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_moisMouseReleased

    private void moisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moisActionPerformed

    private void moisKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_moisKeyReleased

    }//GEN-LAST:event_moisKeyReleased

    private void moisKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_moisKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE )||mois.getText().length()==2)
        {   getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_moisKeyTyped

    private void listDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listDActionPerformed
        try {
            charger();        // TODO add your handling code here:
        } catch (UnknownHostException ex) {
            Logger.getLogger(GestionPersonne.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_listDActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new GestionPersonne().setVisible(true);
                } catch (UnknownHostException ex) {
                    Logger.getLogger(GestionPersonne.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adresse;
    private javax.swing.JButton ajouter;
    private javax.swing.JButton ajouter1;
    private javax.swing.JTextField annee;
    private javax.swing.JTextField any;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jour;
    private javax.swing.JComboBox list;
    private javax.swing.JComboBox listD;
    private javax.swing.JTextField mois;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField num;
    private javax.swing.JTextField numTel;
    private javax.swing.JTextField prenom;
    private javax.swing.JButton supprimer2;
    // End of variables declaration//GEN-END:variables
}
